version: "3.9"
services:
  crypto-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: navidrome
    image: simonphoenix96/crypto-website:latest
    user: 1000:1000 # should be owner of volumes
#    ports:
#      - "999:999"
    restart: unless-stopped
    networks:
      - web
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.basic.port=999"
      - "traefik.basic.frontend.rule=Host:crypto-website.3rdimpact.world"
      - "traefik.basic.protocol=http"
      - "traefik.frontend.auth.basic=crypto-website:$$apr1$$mKnit3Bo$$XBIr1PxupwBJocLLy7L3v/"
EY7AAIsu"
      - "traefik.frontend.headers.SSLRedirect=true"
    expose:
      - "999"
#    logging:
#      driver: gelf
#      options:
#        gelf-address: "udp://0.0.0.0:12201"

    restart: always
networks:
  web:
    external: true

